apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring
  labels:
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: java
    tags.datadoghq.com/version: 0.0.1
spec:
  selector:
    matchLabels:
      app: java-spring
  template:
    metadata:
      labels:
        app: java-spring
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: java
        tags.datadoghq.com/version: 0.0.1
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.37.0
    spec:
      containers:
      - name: java-spring
        image: felipefrx/dd:java
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: DD_LOGS_INJECTION
            value: "true"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-spring
spec:
  type: ClusterIP
  selector:
    app: java-spring
  ports:
  - name: http
    port: 8083
    targetPort: 8080
