apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
  labels:
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: python
    tags.datadoghq.com/version: 0.0.1
spec:
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: python
        tags.datadoghq.com/version: 0.0.1
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: v2.9.1
    spec:
      containers:
      - name: python-flask
        image: felipefrx/dd:python
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: DD_LOGS_INJECTION
            value: "true"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask
spec:
  type: ClusterIP
  selector:
    app: python-flask
  ports:
  - name: http
    port: 8082
    targetPort: 5000
